# conda-recipe/meta.yaml
package:
  name: "syngenes"               # Nome do pacote
  version: "1.0.6"               # Versão do pacote

source:
  path: SynGenes/                 # Caminho para o código-fonte. Certifique-se de que o diretório está no mesmo nível que `meta.yaml`.

build:
  noarch: python                  # Indica que o pacote não é específico de uma arquitetura
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"  # Usa o pip para instalar, o `--no-deps` é adequado para evitar conflito de dependências

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
  run:
    - python >=3.10
    - requests
    - pandas
    - biopython
    - openpyxl

about:
  home: "https://github.com/luanrabelo/SynGenes"
  license: "MIT"
  license_family: MIT
  summary: "A Python class for standardizing mitochondrial and chloroplast gene nomenclatures."
  description: |
    **SynGenes** is a Python class designed to standardize gene nomenclatures for mitochondrial and chloroplast genes. It recognizes various nomenclature variations and converts them into a consistent, standardized format. This tool simplifies the integration and comparison of genetic data from different sources by unifying gene names.
  dev_url: "https://github.com/luanrabelo/SynGenes"
  doc_url: "https://github.com/luanrabelo/SynGenes#readme"

extra:
  recipe-maintainers:
    - luanrabelo
