name: Publish Python package to Anaconda

on: [push, pull_request]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Download and Install Anaconda
        run: |
          wget https://repo.anaconda.com/archive/Anaconda3-2024.10-1-Linux-x86_64.sh -O ~/anaconda.sh
          bash ~/anaconda.sh -b -p $HOME/anaconda
          echo "$HOME/anaconda/bin" >> $GITHUB_PATH  # Adiciona o Anaconda ao PATH

      - name: Update Conda and Install Conda Build
        run: |
          $HOME/anaconda/bin/conda update -n base -c defaults conda -y
          $HOME/anaconda/bin/conda install -n base -c conda-forge conda-build anaconda-client -y

      - name: Verify Conda Build Installation
        run: |
          conda list conda-build

      - name: Build the Conda package
        env:
          CONDA_NO_PLUGINS: true
        run: |
          conda build conda-recipe

      - name: Upload package to Anaconda
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: |
          anaconda login --token $ANACONDA_API_TOKEN
          anaconda upload --skip-existing $HOME/anaconda/conda-bld/noarch/*.tar.bz2
