name: Publish Python package to Anaconda

on: [push, pull_request]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Download and Install Anaconda
        run: |
          wget https://repo.anaconda.com/archive/Anaconda3-2023.07-1-Linux-x86_64.sh -O ~/anaconda.sh
          bash ~/anaconda.sh -b -p $HOME/anaconda
          echo "$HOME/anaconda/bin" >> $GITHUB_PATH  # Adiciona o Anaconda ao PATH
        shell: bash

      - name: Update Conda
        run: conda update -n base -c defaults conda

      - name: Verify Conda and Conda Build Installation
        run: |
          conda --version
          conda list conda-build  # Verifica se o conda-build está instalado
        shell: bash

      - name: Build the Conda package
        env:
          CONDA_NO_PLUGINS: true
        run: |
          conda build conda-recipe
        shell: bash

      - name: Upload package to Anaconda
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: |
          anaconda login --token $ANACONDA_API_TOKEN
          anaconda upload --skip-existing $HOME/anaconda/conda-bld/noarch/*.tar.bz2
        shell: bash
