# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Enviar para PyPI

on:
  release:
    types: [published]

jobs:
  construir-e-publicar:
    name: Construir e Enviar versão para PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Verificar repositório
      uses: actions/checkout@v2
    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine build
    - name: Construir pacote
      run: |
        python -m build
    - name: Gerar token OIDC
      id: gerar_token_oidc
      uses: actions/github-script@v5
      with:
        script: |
          const resp = await github.oidc.create({
            client_id: 'pypi',
            audience: 'https://upload.pypi.org/legacy/'
          });
          const json_data = JSON.stringify({token: resp.data.value});
          core.setOutput('oidc_token', json_data);
    - name: Enviar distribuições do pacote para PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.11
      with:
        verbose: true
        packages-dir: dist/
        user: __token__
        password: ${{ steps.gerar_token_oidc.outputs.oidc_token }}

